// <auto-generated />
namespace CRM2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class eem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eem));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241151391_eem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
